version: '3.7'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-image:dev
    command: >
      sh -c "alembic upgrade head & uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - "8000:8000"

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    image: bot-image:dev
    command: >
      sh -c "alembic upgrade head & python main.py"
    volumes:
      - ./bot:/bot
    env_file:
      - bot/.env
    depends_on:
      - redis
      - backend

  redis:
    image: redis:6.0.6-alpine
    expose:
      - 6379

  db:
    image: postgres:12.0-alpine
    volumes:
      - bot_db:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
    bot_db:
    backend: