"""second

Revision ID: 868e5be5626b
Revises: e0914aa7595b
Create Date: 2024-04-26 23:57:19.551123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868e5be5626b'
down_revision: Union[str, None] = 'e0914aa7595b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('request_sent', sa.Boolean(), nullable=False))
    op.add_column('telegram_users', sa.Column('request_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'request_id')
    op.drop_column('telegram_users', 'request_sent')
    # ### end Alembic commands ###
