"""empty message

Revision ID: 90d3b98b23b3
Revises: 14de58becc33
Create Date: 2024-04-27 02:18:46.733718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d3b98b23b3'
down_revision: Union[str, None] = '14de58becc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('volunteer_id', sa.BigInteger(), nullable=True))
    op.add_column('requests', sa.Column('status', sa.String(), nullable=False))
    op.create_foreign_key(None, 'requests', 'users', ['volunteer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'status')
    op.drop_column('requests', 'volunteer_id')
    # ### end Alembic commands ###
